Get tags for virtual table lines and cells
eclipse-cdt-cloud/tsp-python-client pull request #79
Opened 2024-09-05 19:02 UTC by kavehshahedi

With respect to the following feature in trace-server:
```java
@Schema(description = "Tags for the entire line. " +
        "A bit mask to apply for tagging elements (e.g. table lines, states). " +
        "This can be used by the server to indicate if a filter matches and what action to apply. " +
        "Use 0 for no tags, 1 and 2 are reserved, 4 for 'BORDER' and 8 for 'HIGHLIGHT'.")
int getTags();
```

We can now get the corresponding tags for both lines and cells.
```
0 -> NO_TAGS
1 & 2 -> RESERVED
4 -> BORDER
8 -> HIGHLIGHT
```

2024-09-09 15:05 UTC, bhufmann approved these changes
Looks good to me. Thanks!

2024-09-09 15:06 UTC, bhufmann submitted a review, later dismissed

2024-09-09 15:58 UTC, MatthewKhouzam reviewed
I am looking at the code, I think that you don't need a match case, since you can highlight and border? this is bitfield, not a one hot. Please confirm or deny.

2024-09-09 16:02 UTC, MatthewKhouzam requested changes
I re-reviewed. It's a bit mask, not an enum. You need to handle multiple on.

2024-09-16 18:49 UTC, kavehshahedi commented
@MatthewKhouzam 
I addressed the tags bitmask situation. Right now, instead of processing it as an `enum`, it'll be considered as a bitmask that can handle multiple values (e.g., `BORDER` and `HIGHLIGHT`)

2024-09-20 19:43 UTC, MatthewKhouzam approved these changes

2024-10-04 16:53 UTC, bhufmann approved these changes
LGTM. Thanks!

2024-10-04 16:53 UTC, merged